name: plan_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.13.0
  cloud_firestore: 4.7.1
  firebase_auth: 4.6.1
  firebase_storage: 11.2.1
  google_fonts: 4.0.4
  skeletons: 0.0.3
  intl: 0.17.0
  convex_bottom_bar: 3.2.0
  flutter_form_builder: 7.7.0
  image_picker: 0.8.7+5
  google_sign_in: 6.1.3
  currency_text_input_formatter: 2.1.7
  sign_in_button: 3.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
